[project]
name = "datascipsych-data"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "polars",
    "matplotlib",
    "seaborn",
    "jupyterlab",
    "psifr"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
